// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz-H62aIfVDhFXQQKt3G3KQkcehOfDc90',
    appId: '1:831134894069:web:4805655b538cd4fbe102bc',
    messagingSenderId: '831134894069',
    projectId: 'kri-darkoum',
    authDomain: 'kri-darkoum.firebaseapp.com',
    storageBucket: 'kri-darkoum.firebasestorage.app',
    measurementId: 'G-GJ1T1ZJV2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmeZjDEzgV8K4khhWSegmFop7_4sIPaz4',
    appId: '1:831134894069:android:819549e057b9a31ce102bc',
    messagingSenderId: '831134894069',
    projectId: 'kri-darkoum',
    storageBucket: 'kri-darkoum.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAICqFY2_lUWMwhib-4AvK8mxeKEBMeqZw',
    appId: '1:831134894069:ios:366687d7db51d46ce102bc',
    messagingSenderId: '831134894069',
    projectId: 'kri-darkoum',
    storageBucket: 'kri-darkoum.firebasestorage.app',
    iosBundleId: 'com.example.monProjet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAICqFY2_lUWMwhib-4AvK8mxeKEBMeqZw',
    appId: '1:831134894069:ios:366687d7db51d46ce102bc',
    messagingSenderId: '831134894069',
    projectId: 'kri-darkoum',
    storageBucket: 'kri-darkoum.firebasestorage.app',
    iosBundleId: 'com.example.monProjet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz-H62aIfVDhFXQQKt3G3KQkcehOfDc90',
    appId: '1:831134894069:web:08f0f05d781aead4e102bc',
    messagingSenderId: '831134894069',
    projectId: 'kri-darkoum',
    authDomain: 'kri-darkoum.firebaseapp.com',
    storageBucket: 'kri-darkoum.firebasestorage.app',
    measurementId: 'G-2HS9SMJN6S',
  );
}
